ci:
  autoupdate_schedule: quarterly

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.10
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        stages: [pre-commit, commit-msg]
        exclude_types: [html, csv, bib]
        args: [--check-filenames]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.44.0
    hooks:
      - id: markdownlint
        # MD013: line too long
        # MD024: Multiple headings with the same content
        # MD033: no inline HTML
        # MD041: first line in a file should be a top-level heading
        # MD025: single title
        args: [--disable, MD013, MD024, MD025, MD033, MD041, "--"]

  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout
        args: [--drop-empty-cells, --keep-output]

  - repo: local
    hooks:
      - id: validate-typst
        name: Install and Validate Typst files
        language: system
        entry: |
          bash -c '
          set -e

          TYPST_VERSION="v0.13.1"
          INSTALL_DIR="$HOME/.cache/typst/bin"
          TYPST_PATH="$INSTALL_DIR/typst"

          if [ "$CI" = "true" ] && ! command -v typst >/dev/null && [ ! -x "$TYPST_PATH" ]; then
            mkdir -p "$INSTALL_DIR"
            TMPDIR=$(mktemp -d)
            curl -L "https://github.com/typst/typst/releases/download/${TYPST_VERSION}/typst-x86_64-unknown-linux-musl.tar.xz" -o "$TMPDIR/typst.tar.xz"
            tar -xf "$TMPDIR/typst.tar.xz" -C "$TMPDIR"
            cp "$TMPDIR"/typst-*/typst "$TYPST_PATH"
            chmod +x "$TYPST_PATH"
          fi

          export PATH="$INSTALL_DIR:$PATH"

          for x in "$@"; do
            typst compile "$x" - > /dev/null || exit 255
          done
          ' --

        files: \.typ$
        types: [file]
